# Generated by Django 5.2.10 on 2026-01-21 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='お名前')),
                ('date', models.DateField(verbose_name='来店日')),
                ('time_slot', models.CharField(choices=[('AM', '午前'), ('PM', '午後')], max_length=2, verbose_name='時間帯')),
                ('status', models.CharField(choices=[('confirmed', '予約確定'), ('cancelled', 'キャンセル済み'), ('completed', '来店済み')], default='confirmed', max_length=20, verbose_name='ステータス')),
                ('note', models.TextField(blank=True, verbose_name='備考（ユーザー）')),
                ('admin_memo', models.TextField(blank=True, help_text='スタッフ向けメモ（ユーザーには表示されません）', verbose_name='管理者メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'ordering': ['-date', 'time_slot'],
                'unique_together': {('date', 'time_slot')},
            },
        ),
    ]
