# Generated by Django 5.2 on 2026-01-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='visit_reason',
            field=models.CharField(choices=[('pickup', '受け取り'), ('repair', '修理'), ('consultation', '相談'), ('other', 'その他（備考欄に入力必須）')], default='consultation', max_length=20, verbose_name='来店理由'),
        ),
    ]
