# Generated by Django 5.2.10 on 2026-01-28 00:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_visit_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='メニュー名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('estimated_duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(15)], verbose_name='想定作業時間（分）')),
                ('price_estimate', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='料金目安（数値）')),
                ('price_display', models.CharField(help_text='例: ¥5,000〜', max_length=100, verbose_name='表示用料金テキスト')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '修理・整備メニュー',
                'verbose_name_plural': '修理・整備メニュー',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('confirmed', '予約確定'), ('cancelled', 'キャンセル済み'), ('in_progress', '作業中'), ('completed', '来店済み')], default='confirmed', max_length=20, verbose_name='ステータス'),
        ),
        migrations.CreateModel(
            name='BikeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='メーカー名')),
                ('model_name', models.CharField(max_length=100, verbose_name='モデル名')),
                ('details', models.TextField(verbose_name='修理・整備箇所の詳細')),
                ('has_parts_brought_in', models.BooleanField(default=False, verbose_name='パーツ持ち込み有無')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bike_info', to='reservations.reservation', verbose_name='予約')),
            ],
            options={
                'verbose_name': '自転車情報',
                'verbose_name_plural': '自転車情報',
            },
        ),
        migrations.CreateModel(
            name='BikeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bike_images/%Y/%m/%d/', verbose_name='画像')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時')),
                ('bike_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reservations.bikeinfo', verbose_name='自転車情報')),
            ],
            options={
                'verbose_name': '自転車画像',
                'verbose_name_plural': '自転車画像',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='service_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='reservations.servicemenu', verbose_name='修理・整備メニュー'),
        ),
    ]
