# Generated by Django 5.2.10 on 2026-01-28 01:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_servicemenu_alter_reservation_status_bikeinfo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='日付')),
                ('is_open', models.BooleanField(default=True, verbose_name='営業')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '営業日',
                'verbose_name_plural': '営業日',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='日付')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('is_permanent', models.BooleanField(default=False, help_text='毎週同じ曜日の定休日の場合はチェック', verbose_name='定休日')),
                ('day_of_week', models.IntegerField(blank=True, choices=[(0, '月'), (1, '火'), (2, '水'), (3, '木'), (4, '金'), (5, '土'), (6, '日')], null=True, verbose_name='曜日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '休日',
                'verbose_name_plural': '休日',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='開始時間')),
                ('end_time', models.TimeField(verbose_name='終了時間')),
                ('capacity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='同時対応可能数')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '時間枠',
                'verbose_name_plural': '時間枠',
                'ordering': ['start_time'],
                'unique_together': {('start_time', 'end_time')},
            },
        ),
    ]
