# Generated by Django 5.2.10 on 2026-01-28 01:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_businessday_holiday_timeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='見積金額')),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='確定金額')),
                ('completion_photo', models.ImageField(blank=True, null=True, upload_to='completion_photos/%Y/%m/%d/', verbose_name='完了写真')),
                ('admin_comment', models.TextField(blank=True, help_text='作業内容、注意事項などをメモ', verbose_name='管理者コメント')),
                ('status', models.CharField(choices=[('pending', '予約中'), ('in_progress', '作業中'), ('completed', '完了')], default='pending', max_length=20, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_history', to='reservations.reservation', verbose_name='予約')),
            ],
            options={
                'verbose_name': '作業履歴',
                'verbose_name_plural': '作業履歴',
            },
        ),
    ]
